{
 "title": "Domain Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domains",
    "query": {
     "query": "label_values(domain_probe_success,domain)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "domains" },
  {
   "title": "Domain Expiry Days",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "domain_probe_duration_seconds{domain=~\"$domains\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Status $domains",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domain_probe_success{domain=~\"$domains\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Domain Expiry Days $domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "domain_expiry_days{domain=~\"$domains\"}",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}